package at.tyron.vintagecraft.WorldGen.GenLayers.Continent;

import at.tyron.vintagecraft.WorldGen.GenLayers.GenLayerVC;
import net.minecraft.world.gen.layer.IntCache;

public class GenLayerSmooth extends GenLayerVC {

	public GenLayerSmooth(long par1, GenLayerVC par3GenLayer) {
		super(par1);
		super.parent = par3GenLayer;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	@Override
	public int[] getInts(int x, int z, int xSize, int zSize)
	{
		int xprev = x - 1;
		int zprev = z - 1;
		int xnext = xSize + 2;
		int znext = zSize + 2;
		int[] parentInts = this.parent.getInts(xprev, zprev, xnext, znext);
		int[] intcache = IntCache.getIntCache(xSize * zSize);

		for (int var11 = 0; var11 < zSize; ++var11) {
			for (int var12 = 0; var12 < xSize; ++var12) {
				int var13 = parentInts[var12 + 0 + (var11 + 1) * xnext];
				int var14 = parentInts[var12 + 2 + (var11 + 1) * xnext];
				int var15 = parentInts[var12 + 1 + (var11 + 0) * xnext];
				int var16 = parentInts[var12 + 1 + (var11 + 2) * xnext];
				int var17 = parentInts[var12 + 1 + (var11 + 1) * xnext];

				if (var13 == var14 && var15 == var16) {
					this.initChunkSeed(var12 + x, var11 + z);
					if (this.nextInt(2) == 0)
						var17 = var13;
					else
						var17 = var15;
				}
				else {
					if (var13 == var14)
						var17 = var13;
					if (var15 == var16)
						var17 = var15;
				}
				if(var17 < 0)
					try {
						throw new Exception();
					} catch (Exception e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				intcache[var12 + var11 * xSize] = var17;
			}
		}
		return intcache;
	}
}
