package at.tyron.vintagecraft.WorldGen.GenLayers.Continent;

import net.minecraft.world.gen.layer.GenLayer;
import net.minecraft.world.gen.layer.IntCache;
import at.tyron.vintagecraft.World.BiomeVC;
import at.tyron.vintagecraft.WorldGen.GenLayers.GenLayerVC;

public class GenLayerShore extends GenLayerVC {

	public GenLayerShore(long par1, GenLayerVC par3GenLayer) {
		super(par1);
		this.parent = par3GenLayer;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	@Override
	public int[] getInts(int par1, int par2, int par3, int par4)
	{
		int[] var5 = this.parent.getInts(par1 - 1, par2 - 1, par3 + 2, par4 + 2);
		int[] var6 = IntCache.getIntCache(par3 * par4);

		for (int var7 = 0; var7 < par4; ++var7)
		{
			for (int var8 = 0; var8 < par3; ++var8)
			{
				this.initChunkSeed((long)(var7 + par1), (long)(var8 + par2));
				int var9 = var5[var8 + 1 + (var7 + 1) * (par3 + 2)];
				int var10;
				int var11;
				int var12;
				int var13;

				if ( !BiomeVC.isOceanic(var9) && var9 != BiomeVC.river.biomeID && var9 != BiomeVC.swampland.biomeID && var9 != BiomeVC.HighHills.biomeID)
				{
					var10 = var5[var8 + 1 + (var7 + 1 - 1) * (par3 + 2)];
					var11 = var5[var8 + 1 + 1 + (var7 + 1) * (par3 + 2)];
					var12 = var5[var8 + 1 - 1 + (var7 + 1) * (par3 + 2)];
					var13 = var5[var8 + 1 + (var7 + 1 + 1) * (par3 + 2)];

					if (!BiomeVC.isOceanic(var10) && !BiomeVC.isOceanic(var11) && !BiomeVC.isOceanic(var12) && !BiomeVC.isOceanic(var13))
						var6[var8 + var7 * par3] = var9;
					else
					{
						int beachid = BiomeVC.beach.biomeID;
						if(BiomeVC.isMountainous(var9))
							beachid = BiomeVC.gravelbeach.biomeID;
						var6[var8 + var7 * par3] = beachid;
					}
				}
				else
				{
					var6[var8 + var7 * par3] = var9;
				}

				validateInt(var6, var8 + var7 * par3);
			}
		}
		return var6;
	}
}
